name = "reddit_downloader"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
carotte = ">= 5.0.0 and < 6.0.0"
valkyrie = ">= 4.2.0 and < 5.0.0"
mungo = {
    git =  "https://github.com/auryn31/mungo",
    ref = "be50dead7ce030b43cf2d2a65ca250c5182d5fca"
}

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
