[workspace]
members = ["shard", "reddit-downloader", "auto-poster", "post-subscriber", "discord-interface", "website-api"]
resolver = "2"

[profile.release]
debug = "full"
split-debuginfo = "packed"
lto = "thin"
