[workspace]
members = ["shard", "reddit-downloader", "auto-poster", "post-subscriber", "discord-interface", "user-config-manager", "rslash-manager", "reddit-proxy"]
resolver = "2"

[profile.release]
debug = "full"
split-debuginfo = "packed"
lto = "thin"
