[workspace]

members = [
    "discord-interface",
    "shard",
    "reddit-downloader",
    "rslash-manager",
    "memberships",
    "discord-roles",
    "k8s-interface",
    "posthog",
    "rslash_types"
]

[profile.release]
debug = true
split-debuginfo = "packed"
strip = "debuginfo"