FROM ubuntu:latest


#RUN  apt-get update \
#  && apt-get install -y wget \
#  && rm -rf /var/lib/apt/lists/*
#RUN wget http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.1_1.1.0l-1~deb9u6_amd64.deb
ADD "http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.1_1.1.0l-1~deb9u6_amd64.deb" .
RUN dpkg -i libssl1.1*deb

ADD target/debug/discord-shard /usr/bin/discord-shard
ENTRYPOINT ["/usr/bin/discord-shard"]