[package]
name = "badge-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rouille = "3.6.2"
redis = { version = "*", features = ["aio", "tokio-comp", "connection-manager"] }
log = "*"
env_logger = "*"