[package]
name = "post-subscriber"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.12"
redis = "0.24"
tokio = {version="1.36", features = ["rt-multi-thread"]}
env_logger = "0.11"
log = "*"
posthog = {path = "../posthog"}
mongodb = "*"
tarpc = {version="*", features = ["serde-transport", "tcp", "serde-transport-bincode"]}
anyhow = "*"
futures = "*"
serde_derive = "*"
serde = "*"

post_api = {path = "../post-api"}