{
  description = "R Slash Gleam Downloader";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    nix-gleam = {
      url = "github:arnarg/nix-gleam";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs =
    { nixpkgs, nix-gleam, ... }:
    let
      inherit (nixpkgs) lib;

      forEachSystem = lib.genAttrs lib.systems.flakeExposed;
    in
    {
      packages = forEachSystem (system: {
        default = nix-gleam.packages.${system}.buildGleamApplication {
          # The pname and version will be read from the `gleam.toml`
          # file generated by gleam.
          # But this can be overwritten here too:
          # pname = "my-app";
          # version = "1.2.3";

          # The target is read from the `gleam.toml` file too.
          # Default is "erlang" if nothing is specified but
          # this can also be overwritten here too:
          # target = "javascript";

          # Erlang package can be overridden but defaults to
          # `pkgs.erlang`.
          # erlangPackage = pkgs.erlang_nox;

          src = ./.;
        };
      });
    };
}
