apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-interface
spec:
  selector:
    matchLabels:
      app: discord-interface
  replicas: 1
  template:
    metadata:
        labels:
            app: discord-interface
    spec:
      containers:
        - name: discord-interface
          image: registry.murraygrov.es/discord-interface:dev
          imagePullPolicy: Never # Always
          tty: true
          env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-credentials
                  key: DISCORD_TOKEN
            - name: DISCORD_APPLICATION_ID
              valueFrom:
                secretKeyRef:
                  name: discord-credentials
                  key: DISCORD_APPLICATION_ID
            - name: RUST_LOG
              value: "discord_interface=info"
      imagePullSecrets:
        - name: murraygroves-registry-secret

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: discord-shards
  namespace: r-slash
spec:
  selector:
    matchLabels:
      app: discord-shard
  replicas: 0
  template:
    metadata:
        labels:
            app: discord-shard
    spec:
      containers:
        - name: discord-shard
          image: registry.murraygrov.es/discord-shard:dev
          imagePullPolicy: Never # Always
          tty: true
          env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-credentials
                  key: DISCORD_TOKEN
            - name: DISCORD_APPLICATION_ID
              valueFrom:
                secretKeyRef:
                  name: discord-credentials
                  key: DISCORD_APPLICATION_ID
            - name: RUST_LOG
              value: "discord_shard=debug"
            - name: SHARD_ID
              value: "0"

      imagePullSecrets:
        - name: murraygroves-registry-secret
  serviceName: discord-shard
