apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJyZWdpc3RyeS5tdXJyYXlncm92LmVzIjogewoJCQkiYXV0aCI6ICJiWFZ5Y21GNE1qcEJiamh1ZVcxdmRYTWgiCgkJfQoJfQp9
kind: Secret
metadata:
  name: murraygroves-registry-secret
  namespace: r-slash
type: kubernetes.io/dockerconfigjson
