apiVersion: v1
kind: Namespace
metadata:
  name: r-slash

---

apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJyZWdpc3RyeS5tdXJyYXlncm92LmVzIjogewoJCQkiYXV0aCI6ICJiWFZ5Y21GNE1qcEJiamh1ZVcxdmRYTWgiCgkJfQoJfQp9
kind: Secret
metadata:
  name: murraygroves-registry-secret
  namespace: r-slash
type: kubernetes.io/dockerconfigjson

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: api-cluster-role
  namespace: devops-tools
rules:
  - apiGroups:
        - ""
        - apps
        - autoscaling
        - batch
        - extensions
        - policy
        - rbac.authorization.k8s.io
    resources:
      - pods
      - componentstatuses
      - configmaps
      - daemonsets
      - statefulsets
      - deployments
      - deployments.apps
      - events
      - endpoints
      - horizontalpodautoscalers
      - ingress
      - jobs
      - limitranges
      - namespaces
      - nodes
      - pods
      - persistentvolumes
      - persistentvolumeclaims
      - resourcequotas
      - replicasets
      - replicationcontrollers
      - serviceaccounts
      - services
      - secrets
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: api-cluster-role-binding
subjects:
- namespace: r-slash
  kind: ServiceAccount
  name: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: api-cluster-role

---

apiVersion: v1
kind: Secret
metadata:
  name: discord-credentials
type: Opaque
stringData:
    DISCORD_TOKEN: "MjkxMjU1OTg2NzQyNjI0MjU2.GeHJNI.vIQtFk9940KMWhPbLl9dny59I8RtSDgBleMagk"
    DISCORD_APPLICATION_ID: "291255986742624256"

---

apiVersion: v1
kind: Secret
metadata:
  name: reddit-credentials
type: Opaque
stringData:
    REDDIT_TOKEN: "AbqYCMOt7mkTDFTYid-e2UxA2Gs"
    REDDIT_CLIENT_ID: "lHbWNxacD4UKfw"
---

apiVersion: v1
kind: Secret
metadata:
  name: configuration
type: Opaque
stringData:
    SUBREDDIT_LIST: "gifs,pics"

---
apiVersion: v1
kind: Secret
metadata:
  name: gfycat-credentials
type: Opaque
stringData:
    GFYCAT_CLIENT: "2_CJUJYg"
    GFYCAT_SECRET: "sOpBYyzZeewcGgYf264SFnHeggtmBq7MfrE8l_1ZvxDFWSn1fAQlLBDfbc0eMuhM"

---
apiVersion: v1
kind: Secret
metadata:
  name: imgur-credentials
type: Opaque
stringData:
    IMGUR_CLIENT: "63f81848dd5f5a1"
    IMGUR_SECRET: "8e4fac15622062409e53d1d4c2ce1d3cecb914a7"