[package]
name = "user-config-manager"
version = "0.1.0"
edition = "2024"

[dependencies]
mongodb = "3"
serenity = { git = "https://github.com/serenity-rs/serenity.git", branch = "next", features = [
	"model",
] }
serde = { version = "1.0.219", features = ["derive"] }
anyhow = "*"
